#!/bin/sh

FLAGS=""
if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
	FLAGS="--depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
	git init
	git remote add origin ${DRONE_REMOTE_URL}
fi

set -e
set -x


git fetch ${FLAGS} origin +refs/pull/${DRONE_PULL_REQUEST}/merge:pull/${DRONE_PULL_REQUEST}/merge
git checkout pull/${DRONE_PULL_REQUEST}/merge
